In [1]:
import pandas as pd


In [2]:
frame = pd.read_csv('data/sample_cleansingWine.csv')

In [3]:
frame

id  sweet  acidity  body  tannin  type
0    161931    1.0      3.0   5.0     4.0   1.0
1    147249    1.0      4.0   5.0     4.0   1.0
2    166794    1.0      3.0   5.0     3.0   1.0
3    162289    1.0      3.0   4.0     4.0   1.0
4    158963    1.0      4.0   4.0     4.0   1.0
..      ...    ...      ...   ...     ...   ...
995  147749    5.0      2.0   3.0     2.0   1.0
996  149498    5.0      4.0   3.0     1.0   2.0
997  145753    5.0      2.0   2.0     1.0   2.0
998  166465    5.0      4.0   4.0     1.0   2.0
999  142838    5.0      1.0   2.0     3.0   1.0

[1000 rows x 6 columns]

index 0 : id


In [4]:
np_frame = frame.to_numpy()

In [5]:
len(np_frame)

1000

In [24]:
np_frame

array([[1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00],
       [1.47249e+05, 1.00000e+00, 4.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00],
       [1.66794e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 3.00000e+00,
        1.00000e+00],
       ...,
       [1.45753e+05, 5.00000e+00, 2.00000e+00, 2.00000e+00, 1.00000e+00,
        2.00000e+00],
       [1.66465e+05, 5.00000e+00, 4.00000e+00, 4.00000e+00, 1.00000e+00,
        2.00000e+00],
       [1.42838e+05, 5.00000e+00, 1.00000e+00, 2.00000e+00, 3.00000e+00,
        1.00000e+00]])

In [29]:
same_class = []
other_class = []
wine1 = np_frame[0]
for wine in np_frame:
    same_point = 0
    if wine1[1] == wine[1]:
        same_point+=1
    if wine1[2] == wine[2]:
        same_point+=1
    if wine1[3] == wine[3]:
        same_point+=1
    if wine1[4] == wine[4]:
        same_point+=1
    if wine1[5] == wine[5]:
        same_point+=1
    
    if same_point > 2:
        same_class.append(wine)
    else:
        other_class.append(wine)
        


In [30]:
len(same_class)

117

In [32]:
same_class

[array([1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.47249e+05, 1.00000e+00, 4.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.66794e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 3.00000e+00,
        1.00000e+00]),
 array([1.62289e+05, 1.00000e+00, 3.00000e+00, 4.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.58963e+05, 1.00000e+00, 4.00000e+00, 4.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.62017e+05, 1.00000e+00, 3.00000e+00, 4.00000e+00, 3.00000e+00,
        1.00000e+00]),
 array([1.48368e+05, 1.00000e+00, 3.00000e+00, 4.00000e+00, 3.00000e+00,
        1.00000e+00]),
 array([1.38238e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.52908e+05, 1.00000e+00, 3.00000e+00, 3.00000e+00, 3.00000e+00,
        1.00000e+00]),
 array([1.63159e+05, 1.00000e+00, 3.00000e+00, 4.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.45193e+05, 1.00000e+00, 3.0000

In [31]:
len(other_class)

883

In [33]:
datasets = []
for same in same_class:
    for other in other_class:
        data = []
        data.append(wine1)
        data.append(same)
        data.append(other)
        datasets.append(data)
        

In [35]:
len(datasets)

103311

In [16]:
wine_same_class = []
wine_other_class = []
for wine in np_frame:
    same_class = []
    other_class = []
    for wine_other in np_frame:
        same_point = 0
        if wine[1] == wine_other[1]:
            same_point+=1
        if wine[2] == wine_other[2]:
            same_point+=1
        if wine[3] == wine_other[3]:
            same_point+=1
        if wine[4] == wine_other[4]:
            same_point+=1
        if wine[5] == wine_other[5]:
            same_point+=1
        
        if same_point > 2:
            same_class.append(wine_other)
        else:
            other_class.append(wine_other)
    
    wine_same_class.append(same_class)
    wine_other_class.append(other_class)
            


In [7]:
len(wine_same_class)

1000

In [8]:
len(wine_same_class[0])

117

In [18]:
total_wine_num = 1000
datasets = []
for i in range(10):
    main_wine = np_frame[i]
    same_class = wine_same_class[i]
    other_class = wine_other_class[i]
    for same in same_class:
        for other in other_class:
            data = []
            data.append(main_wine)
            data.append(same)
            data.append(other)
            datasets.append(data)

In [19]:
len(datasets)

1211459

In [17]:
wine_same_class[0]

[array([1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.47249e+05, 1.00000e+00, 4.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.66794e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 3.00000e+00,
        1.00000e+00]),
 array([1.62289e+05, 1.00000e+00, 3.00000e+00, 4.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.58963e+05, 1.00000e+00, 4.00000e+00, 4.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.62017e+05, 1.00000e+00, 3.00000e+00, 4.00000e+00, 3.00000e+00,
        1.00000e+00]),
 array([1.48368e+05, 1.00000e+00, 3.00000e+00, 4.00000e+00, 3.00000e+00,
        1.00000e+00]),
 array([1.38238e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.52908e+05, 1.00000e+00, 3.00000e+00, 3.00000e+00, 3.00000e+00,
        1.00000e+00]),
 array([1.63159e+05, 1.00000e+00, 3.00000e+00, 4.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.45193e+05, 1.00000e+00, 3.0000

In [20]:
datasets[0]

[array([1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.68474e+05, 1.00000e+00, 4.00000e+00, 3.00000e+00, 1.00000e+00,
        2.00000e+00])]

In [21]:
datasets[1]

[array([1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.61398e+05, 1.00000e+00, 5.00000e+00, 4.00000e+00, 1.00000e+00,
        2.00000e+00])]

In [22]:
datasets[2]

[array([1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.49216e+05, 1.00000e+00, 5.00000e+00, 3.00000e+00, 3.00000e+00,
        1.00000e+00])]

In [23]:
import torch

In [34]:
def one_hot_encoding(wine):
        '''
        len 22 vector
        5 + 5 + 5 + 5 + 5
        '''
        wine_vector = torch.zeros((5 * 5))
        for i, value in enumerate(wine[1:]):
            print(i, value)
            print(i*5 + (int(value)-1))
            wine_vector[i*5 + (int(value)-1)] = 1
            
        return wine_vector

In [25]:
datasets[0]

[array([1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
        1.00000e+00]),
 array([1.68474e+05, 1.00000e+00, 4.00000e+00, 3.00000e+00, 1.00000e+00,
        2.00000e+00])]

In [35]:
main_wine = datasets[0][0]

In [36]:
main_wine

array([1.61931e+05, 1.00000e+00, 3.00000e+00, 5.00000e+00, 4.00000e+00,
       1.00000e+00])

In [37]:
wine_vector = one_hot_encoding(main_wine)

0 1.0
0
1 3.0
7
2 5.0
14
3 4.0
18
4 1.0
20


In [38]:
print(wine_vector)

tensor([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 1., 0., 0., 0., 0.])
